### PR TITLE
JS improvements and Clone field compatibility

### PR DESCRIPTION
**Pull request by R3dRidle**
This pull-request fixes 2 issues:
https://github.com/flyntwp/acf-hide-layout/issues/2
https://github.com/flyntwp/acf-hide-layout/issues/3

### CODE REVIEW

**Comment by harunbleech** [comment]
Hi @R3dRidle, 

thank you for the research and fixes but it seems this isn't necessary as with the latest ACF version the default ACF "Duplicate layout" option works. When you duplicate the field and save the page it is hidden.

Could you check this again?

**Comment by R3dRidle** [comment]
Hello,

The issue is not about the "Duplicate layout" otion, but about the actual "Clone" field: https://www.advancedcustomfields.com/resources/clone/

This doesn't work. On my pages it all works fine, but not on other post types with a cloned field from pages.

That's what this bug is about:
https://github.com/flyntwp/acf-hide-layout/issues/2?web=1&wdLOR=c67C84057-D90F-4415-BEB9-620E2330B0AE

I could send you guys the login to our test WP installation via email to check it out.



This one https://github.com/flyntwp/acf-hide-layout/issues/3?web=1&wdLOR=c82944D13-73AA-489A-90F1-961763815CEB is indeed fixed with the 
if(window.acf){

Kind regards
Dennis

**Comment by harunbleech** [comment]
Hi @R3dRidle,

we have updated the code that seems to fix it. 

Could you also test it with your example?

Best,
Harun

**Comment by R3dRidle** [comment]
@harunbleech  Yes that works perfectly.

I wanted to propose 1 little change to the CSS too for UX.
This way when a field is disabled (hidden) you can't change the content. It's more logical to the endusers that it's a disabled field.

`
.acf-layout-hidden .acf-fields * {
    pointer-events: none;
}
.acf-layout-hidden .acf-fields * {
    pointer-events: none;
}
`

**Comment by R3dRidle** [comment]
@harunbleech 
Hello, any update on this? It works on my end too.
Also can you consider the CSS additions?

**Comment by R3dRidle** [comment]
@harunbleech 
When will the update be live on https://nl.wordpress.org/plugins/acf-hide-layout/ ?

**Comment by harunbleech** [comment]
Hi @R3dRidle, we have added your CSS recommendations and updated the plugin.

**Pull request closed without merging**
